name: testing
on:
  workflow_dispatch:
  push:
    branches:
      main

jobs:
  test-code:
    runs-on: ubuntu-22.04
    environment: test
    env:
      MONGO_URL: ${{ secrets.MONGO_URL }}
      MONGO_USER: ${{ vars.MONGO_USER }}
      MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
    container: python:3.8.18-bullseye
    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: ${{ vars.MONGO_USER }}
          MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      #- name: set up py
      #  uses: actions/setup-python@v4
      #  with:
      #    python-version: 3.8
      - name: install requirements.txt
        run: pip install -r requirements.txt
      #- name: create mongodb container
      #  run: |
      #    docker run -d -p 27017:27017 --name some-mongo \
      #    -e MONGO_INITDB_ROOT_USERNAME=root \
      #    -e MONGO_INITDB_ROOT_PASSWORD=example \
      #    mongo
      - name: run pytest
        id: run-pytest
        run: |
          echo "$MONGO_USER"
          echo "$MONGO_PASSWORD"
          pytest


